# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateNetwork <- function(X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtM1, M1tM1PlusRhoInv, M1tY, XtY, L) {
    .Call('_HDMAADMM_estimateNetwork', PACKAGE = 'HDMAADMM', X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtM1, M1tM1PlusRhoInv, M1tY, XtY, L)
}

estimatePathwayLasso <- function(X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtM1, M1tM1PlusRhoInv, M1tY, XtY, kappa, nu) {
    .Call('_HDMAADMM_estimatePathwayLasso', PACKAGE = 'HDMAADMM', X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtM1, M1tM1PlusRhoInv, M1tY, XtY, kappa, nu)
}

cast_numeric <- function(input) {
    .Call('_HDMAADMM_cast_numeric', PACKAGE = 'HDMAADMM', input)
}

fMatProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatTransProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatTransProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatSolve <- function(X, Y, is_sym_pd = FALSE, is_invertible = FALSE) {
    .Call('_HDMAADMM_fMatSolve', PACKAGE = 'HDMAADMM', X, Y, is_sym_pd, is_invertible)
}

fMatInv <- function(X, is_sym_pd = FALSE) {
    .Call('_HDMAADMM_fMatInv', PACKAGE = 'HDMAADMM', X, is_sym_pd)
}

