# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fMatProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatTransProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatTransProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatChol <- function(X) {
    .Call('_HDMAADMM_fMatChol', PACKAGE = 'HDMAADMM', X)
}

singleModalityAdmmFit <- function(X, Y, M1, alphaInit, betaInit, gammaInit, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, penaltyType, penaltyParameters, maxIter, tol, verbose) {
    .Call('_HDMAADMM_singleModalityAdmmFit', PACKAGE = 'HDMAADMM', X, Y, M1, alphaInit, betaInit, gammaInit, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, penaltyType, penaltyParameters, maxIter, tol, verbose)
}

