# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateElasticNet <- function(X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY) {
    .Call('_HDMAADMM_estimateElasticNet', PACKAGE = 'HDMAADMM', X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY)
}

estimateNetwork <- function(X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY, L) {
    .Call('_HDMAADMM_estimateNetwork', PACKAGE = 'HDMAADMM', X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY, L)
}

estimatePathwayLasso <- function(X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY, kappa, nu) {
    .Call('_HDMAADMM_estimatePathwayLasso', PACKAGE = 'HDMAADMM', X, Y, M1, alpha, beta, gamma, tauAlpha, tauBeta, rho, lambda1a, lambda1b, lambda1g, lambda2a, lambda2b, XtX, XtXPlusRhoInv, XtM1, M1tM1PlusRhoInv, M1tY, XtY, kappa, nu)
}

fMatProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatTransProd <- function(X, Y, is_X_symmetric = FALSE) {
    .Call('_HDMAADMM_fMatTransProd', PACKAGE = 'HDMAADMM', X, Y, is_X_symmetric)
}

fMatInv <- function(X, is_sym_pd = FALSE) {
    .Call('_HDMAADMM_fMatInv', PACKAGE = 'HDMAADMM', X, is_sym_pd)
}

fMatChol <- function(X) {
    .Call('_HDMAADMM_fMatChol', PACKAGE = 'HDMAADMM', X)
}

